version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_usuarios
    environment:
    - POSTGRES_DB=usuarios_db
    - POSTGRES_USER=localhost
    - POSTGRES_PASSWORD=12345678
    ports:
      - 5432:5432

  api:
    build: .
    container_name: api_usuarios
    ports:
      - 9091:9091
    depends_on:
      - postgres
